### ISSUE TITLE
prefix(): expected first argument to be an Array or a Hash, got ""

### ISSUE THREAD

**Issue by baldurmen** [voxpupuli/puppet-icinga2#268] opened 2017-03-24 22:23 UTC
OS: Debian Jessie
Puppet: `3.7.2`
Facter: `2.2.0`
Ruby:  `2.1.5`
Puppetlabs-concat: `2.2.0`
Puppetlabs-stdlib: `4.13.1`
Icinga2: `2.6.0-2` (from the Debian repository)

I get the error using either `v1.1.1` or `v1.2.0`.

When I run the `idomysql` class, I get this error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: prefix(): expected first argument to be an Array or a Hash, got "" at /etc/puppet/environments/server/modules/icinga2/manifests/config.pp:20 on node icinga2
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
i'm using the class call in the examples:

```
class{ '::icinga2::feature::idomysql':
  user          => 'icinga2',
  password      => 'supersecret',
  database      => 'icinga2',
  import_schema => true,
}
```

Including only the `icinga2` class works fine.

I've tried restarting the puppet master to clear the cache without success. My error message looks like #267 but seems a little different.

**Comment by lbetz** [comment] 2017-03-26 06:45
Did you clear your puppet master cache?

**Comment by baldurmen** [comment] 2017-03-26 15:51
I have to say this is the first time I ever have to do this, but yes, I ran `rm /var/lib/puppet/client_data/catalog/*`.

If that is not enough to clear the cache, please tell me how.

**Comment by Reamer** [comment] 2017-03-26 16:36
A restart of Puppetserver should be enough to clear the cache. Puppetserver has also a curl command. You can find more information under this [link](https://docs.puppet.com/puppetserver/latest/admin-api/v1/environment-cache.html)

**Comment by baldurmen** [comment] 2017-03-26 17:04
I'm not running Puppet Server, only a WEBrick Puppet master.

I did restart the master a few times just to be sure.

**Comment by bobapple** [comment] 2017-03-27 09:16
@baldurmen are you including the `::icinga2` class when using `::icinga2::feature::idomysql`? If not, you should.

Also, this module requires at least Puppet 3.8. You probably should update your puppet master.

**Comment by baldurmen** [comment] 2017-03-27 17:00
I'm calling icinga2 this way:

```
class {
  '::icinga2':
    manage_package => false;

  '::icinga2::feature::idomysql':
    user          => 'icinga2',
    password      => 'mysupersecretpasswd',
    database      => 'icinga2',
    import_schema => true;
}
```
As for Puppet 3.8, I'm using the Debian packages from the Debian repository. Next step is Puppet 4.8 and I'm not ready to make that step just yet.

Is Puppet 3.7 so different from Puppet 3.8 that it could make this crash?

**Comment by lbetz** [comment] 2017-03-28 16:01
Works this syntax on puppet 3? I only now it from puppet 4.

**Comment by baldurmen** [comment] 2017-03-29 13:24
#199 states that this should work with Puppet 3.8.6. I'll try to update through old jessie-backports packages to that version tomorrow and see if it fixes my problem.

**Comment by baldurmen** [comment] 2017-03-30 19:44
I updated to Puppet `3.8.5` and I get the same problem. This seems to be a real bug, not just something caused by me using a version of Puppet that is not supported.

**Comment by lbetz** [comment] 2017-04-03 09:59
I cannot reproduce that. Please post your complete manifest.

**Comment by bobapple** [comment] 2017-04-06 12:51
@baldurmen can you post your puppet code so we have a better chance to reproduce this?

**Comment by baldurmen** [comment] 2017-04-06 20:43
I'm not sure I understand your request. The only "puppet code" i used to try to use this module is:

```
class {
  '::icinga2':
    manage_package => false;

  '::icinga2::feature::idomysql':
    user          => 'icinga2',
    password      => 'mysupersecretpasswd',
    database      => 'icinga2',
    import_schema => true;
}
```

I put this in a class named `icinga2-meta`, called from hiera.

**Comment by lbetz** [comment] 2017-04-07 04:23
This snippet isn't run capable. You use manage_package => false, how the package installation is done? How the database management? Please post the complete code.

**Comment by baldurmen** [comment] 2017-04-07 18:01
Thanks, that is clearer.

This is how my meta module is organized:

```.
└── manifests
    ├── config.pp
    ├── init.pp
    └── install.pp
```
init.pp:
```
class icinga2-meta () {

include ::icinga2-meta::config
include ::icinga2-meta::install
}
```
install.pp:
```
class icinga2-meta::install inherits icinga2-meta {

 apt::preferences_snippet {
    [ 'icinga2',
      'icinga2-ido-mysql' ]:
        release  => 'jessie-backports',
        priority => 999,
        before   => Package['icinga2'];
 }

 package {
    [ 'icinga2',
      'icinga2-ido-mysql' ]:
        ensure => present;
  }
}
```
config.pp
```
class icinga2-meta::config inherits icinga2-meta {

  file {
    '/data':
      ensure => directory;
  }

  # MySQL DB

  mysql_database {
    'icinga2':
      ensure => present;
  }

  mysql_user {
    'icinga2@localhost':
      ensure        => present,
      password_hash => '*hash';
  }

  mysql_grant {
    'icinga2@localhost/icinga2.*':
      ensure     => 'present',
      options    => ['GRANT'],
      privileges => ['ALL'],
      table      => 'icinga2.*',
      user       => 'icinga2@localhost';
  }

  class {
    '::icinga2':
      manage_package => false;

    '::icinga2::feature::idomysql':
      user          => 'icinga2',
      password      => 'supersecret',
      database      => 'icinga2',
      import_schema => true;
  }
}
```

Note that I'm not using the puppetlabs apt module but another one. I'm using the puppetlabs mysql module but I'm not using the short form to stay explicit in my manifests.

I'm not sure why you need this though. How I install the icinga2 package from Debian jessie-backports or how I create my DB should not change anything.

**Comment by lbetz** [comment] 2017-04-10 11:42
Sorry, but your code runs 'great' on my debian jessie, puppet 3.7.2 etc.

**Comment by bobapple** [comment] 2017-04-10 11:54
@baldurmen can you give us any other hints on how to reproduce this issue?

**Comment by lbetz** [comment] 2017-04-10 13:52
I only get this error by swapping both icinga2 classes like:

```
class {
  '::icinga2::feature::idomysql':
    user          => 'icinga2',
    password      => 'mysupersecretpasswd',
    database      => 'icinga2',
    import_schema => true;

  '::icinga2':
    manage_package => false;
}
```

It's an ordering problem.... and not an ordering between resouces but rather a ordering of parsing variables. What's happened when you replace that snippet with the following?

```
class {
  '::icinga2':
    manage_package => false,
}

class {
    '::icinga2::feature::idomysql':
      user          => 'icinga2',
      password      => 'mysupersecretpasswd',
      database      => 'icinga2',
      import_schema => true,
}
```

**Comment by bobapple** [comment] 2017-04-12 13:40
I'm closing this issue since we're not able to influence the order of variable parsing. Please refer to the [usage section](https://github.com/Icinga/puppet-icinga2#usage) of this modules documentation.

**Closed as completed by bobapple** 2017-04-12 13:40 UTC
Labels: invalid
