### ISSUE TITLE
auto-quoting issues

### ISSUE THREAD

**Issue by fredrik-eriksson** [voxpupuli/puppet-icinga2#226] opened 2017-02-03 17:08 UTC
Hi,

First of all: Thank you for developing this module. It is very useful as it is, but there are a few things I think can be better. The most important of those things are the automatic quoting; because it seems to do more harm than good.

Consider the following service:

```
  icinga2::object::service {
    'ping4_interface_':
      target  => $target_file,
      check_command => 'ping4',
      apply   => 'interface => opts in host.vars.network.interfaces',
      assign => [
        'opts.address',
      ],  
      vars             => {
        'ping_address' => 'opts.address',
        'ping_cpl'     => 'getvar(host.vars.ping_cpl, 40)',
      };  
}
```
This doesn't work because the parser doesn't realize that opts is a valid local object, resulting in this object:
```
apply Service for (interface => opts in host.vars.network.interfaces) to Host {

  vars.ping_address = "opts.address"
  vars.ping_cpl = getvar(host.vars.ping_cpl, 40) 
  check_command = "ping4"
  assign where "opts.address"
}
```

The function detection also messes up up in some spectacular ways. If I want a load test over ssh I create an object like  so:
```
  icinga2::object::service {
    'load-template':
      target        => $target_file,
      check_command => 'by_ssh',
      vars          => {
        'by_ssh_command'   => '/usr/local/libexec/nagios/check_load',
        'by_ssh_arguments' => {
          '-w' => {
            'value'       => '$load_wload1$,$load_wload5$,$load_wload15$',
            'description' => 'Exit with WARNING status if load average exceeds WLOADn',
          },  
          '-c' => {
            'value'       => '$load_cload1$,$load_cload5$,$load_cload15$',
            'description' => "Exit with CRITICAL status if load average exceed CLOADn; the load average format is the same used by 'uptime' and 'w'",
          },  
          '-r' => {
            'value'       => '$load_percpu$',
            'description' => 'Divide the load averages by the number of CPUs (when possible)',
          },  
        },  
        'by_ssh_logname'   => 'monitor',
      },  
      template   => true;
  }
```
But the resulting object apparently think the entire description for '-r' is a function:
```
template Service "load-template"  {
  vars.by_ssh_command = "/usr/local/libexec/nagios/check_load"
  vars.by_ssh_arguments["-w"] = {
    value = "$load_wload1$,$load_wload5$,$load_wload15$"
    description = "Exit with WARNING status if load average exceeds WLOADn"
  }
  vars.by_ssh_arguments["-c"] = {
    value = "$load_cload1$,$load_cload5$,$load_cload15$"
    description = "Exit with CRITICAL status if load average exceed CLOADn; the load average format is the same used by 'uptime' and 'w'"
  }
  vars.by_ssh_arguments["-r"] = {
    value = "$load_percpu$"
    description = Divide the load averages by the number of CPUs ("when possible")
  }
  vars.by_ssh_logname = "monitor"
  check_command = "by_ssh"
}
```

Some things I don't understand at all how they come to be. Using dicts as values for the arguments in vars.by_ssh_arguments is usually fine, but what happens if you try to use just strings?
```
  icinga2::object::service {
    'ntp_time-template':
      target        => $target_file,
      check_command => 'by_ssh',
      vars          => {
        'by_ssh_command'   => '/usr/local/libexec/nagios/check_ntp_time',
        'by_ssh_arguments' => {
                '-H' => '$ntp_address$',
                '-p' => '$ntp_port$',
                '-q' => '$ntp_quit$',
                '-w' => '$ntp_warning$',
                '-c' => '$ntp_critical$',
                '-o' => '$ntp_timeoffset$',
                '-t' => '$ntp_timeout$',
        },  
        'by_ssh_logname'   => 'monitor',
      },  
      template   => true;
  }
```
Well, the values are correct, but why are the flags double-quoted?
```
template Service "ntp_time-template"  {
  vars.by_ssh_command = "/usr/local/libexec/nagios/check_ntp_time"
  vars.by_ssh_arguments[""-H""] = "$ntp_address$"
  vars.by_ssh_arguments[""-p""] = "$ntp_port$"
  vars.by_ssh_arguments[""-q""] = "$ntp_quit$"
  vars.by_ssh_arguments[""-w""] = "$ntp_warning$"
  vars.by_ssh_arguments[""-c""] = "$ntp_critical$"
  vars.by_ssh_arguments[""-o""] = "$ntp_timeoffset$"
  vars.by_ssh_arguments[""-t""] = "$ntp_timeout$"
  vars.by_ssh_logname = "monitor"
  check_command = "by_ssh"
}
```

issue #221 is another of the problems with the auto-quoting; simply leaving the quoting to the user would solve these problems. I guess that the auto-quoting is made to simplify module usage - perhaps to not require the user to know all the icinga2 syntax to work with it. But frankly, with the current auto-quoting it just makes it more difficult to work with.

**Comment by lbetz** [comment] 2017-02-04 20:24
Hi Frederik,

Thanks for your interest and your feedback.

Dropping this feature will make it difficult to assign strings to icinga attributes. Then you have to do something like this

attr => '"string"'     to get      attr = "string"

attr => "\"string\" in host.templates and $puppet_variable"     to get     attr = "string" in host.templates and content_puppet_variable"

Or we've to implement all values as strings for using a simple expression

attr => 'string' 

But then the problem is to use expressions based on objects or variables.

attr => 'host.address'    you'll get     attr = "host.address"

All that put us to implement this parser. Perhaps we can add an option to deactivate the parser, globally or for the actual object?

Your first described problem has to be fixed by closing your issue #227. The thing with the description I'll analyze at next. The style problem with ""-H"" as hash key should be easy to fix, I think.

At last a tipp to define check_commands executed by ssh. In Icinga 2 you can combine check commands, i.e. by_ssh and load:

template CheckCommand "by_ssh_base" {
  import "by_ssh"

  vars.by_ssh_plugindir = PluginDir
}

object CheckCommand "by_ssh_load" {
        import "load"
        vars.by_ssh_arguments = arguments
        arguments = null
        vars.by_ssh_command = "$by_ssh_plugindir$/check_load"
        import "by_ssh_base"
}  

This will make using the load macros possible:

object Host "host.eaxmple.org" |
        ....
        vars.load_warning = ....
}

Bye
Lennart

**Comment by lbetz** [comment] 2017-02-04 20:53
'description' => 'Divide the load averages by the number of CPUs (when possible)',

The troublemaker is the ()-statement. Please do not use '(' or ')' in strings if you won't make an expression and you wanna get a string in your Icinga 2 configuration.

**Comment by fredrik-eriksson** [comment] 2017-02-05 16:47
Thanks for the respoonse and fixes! After reading the code more closely I realized that calling for dropping auto-quoting was a bit to harsh (and considering backward compatibility it's actually a pretty bad idea). I do like the idea of being able to disable auto-quoting on a per-object base though. Perhaps a "autoquote" option that defaults to true could be added to the objects. Then you can disable auto-quoting if you want to use parenthesis and/or arrays and other stuff that the auto-quoter can't handle.

Thanks for the tip on ssh-command execution, I hadn't thought about that :)

**Closed as completed** 2017-02-07 07:39 UTC
Labels: wontfix
